server:
  port: 8301

spring:
  application:
    name: ribbon-test
  service-url:
    user-service: http://user-test
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8101/eureka/

service-url:
  user-service: http://user-test
